name: Deploy to InfinityFree

on:
  push:
    branches: [main] # branche à déployer
  workflow_dispatch: # + bouton manuel dans l'onglet Actions

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"

      - name: Install Composer dependencies
        run: composer install --no-dev --optimize-autoloader --no-interaction

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          local-dir: ./
          server-dir: htdocs/
          exclude: |
            **/.git*
            **/.git*/**
            **/.github/**
            **/tests/**
            **/node_modules/**
            **/.env
            database/**
            _deploy.php
            deploy.zip
